name: CI

on:
  workflow_dispatch:  # This event allows the workflow to be triggered by the API

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run tests
        run: echo "Running tests..."
